In [1]:
import pandas as pd

df = pd.read_excel('starbucks_drinkMenu_expanded.xlsx')

In [3]:
df['Calories'] = pd.to_numeric(df['Calories'], errors='coerce')
df['Sugars (g)'] = pd.to_numeric(df['Sugars (g)'], errors='coerce')
df['Total Fat (g)'] = pd.to_numeric(df['Total Fat (g)'], errors='coerce')

category_performance = df.groupby('Beverage_category').agg(
    Total_Drinks=('Beverage', 'count'),
    Avg_Calories=('Calories', 'mean'),
    Avg_Sugar_g=('Sugars (g)', 'mean'),
    Avg_Fat_g=('Total Fat (g)', 'mean')
).sort_values(by='Avg_Calories', ascending=False)

In [4]:
print("--- Category Performance Summary ---")
display(category_performance)

--- Category Performance Summary ---

,Total_Drinks,Avg_Calories,Avg_Sugar_g,Avg_Fat_g
Beverage_category,,,,
Smoothies,9,282.222222,36.777778,2.333333
Frappuccino® Blended Coffee,36,276.944444,57.083333,3.002778
Signature Espresso Drinks,40,250.000000,38.600000,5.275000
Frappuccino® Blended Crème,13,233.076923,48.461538,1.850000
Tazo® Tea Drinks,52,177.307692,30.307692,2.540385
Frappuccino® Light Blended Coffee,12,162.500000,32.416667,1.258333
Classic Espresso Drinks,58,140.172414,16.965517,3.127586
Shaken Iced Beverages,18,114.444444,26.000000,0.472222
Coffee,4,4.250000,0.000000,0.100000

In [5]:
df['Calorie_Level'] = df['Calories'].apply(lambda x: 'Low/Moderate Calorie' if x <= 200 else 'High Calorie')

calorie_segment = df['Calorie_Level'].value_counts()
print("\n--- Calorie Segment Breakdown ---")
print(calorie_segment)

--- Calorie Segment Breakdown ---
Calorie_Level
Low/Moderate Calorie    142
High Calorie            100
Name: count, dtype: int64

In [6]:
size_analysis = df.groupby('Beverage_prep')['Calories'].mean().sort_values(ascending=False)
print("\n--- Size (Beverage Prep) Wise Average Calories ---")
display(size_analysis)

--- Size (Beverage Prep) Wise Average Calories ---

Beverage_prep
Whole Milk            283.750000
Venti Nonfat Milk     260.000000
2% Milk               218.000000
Grande Nonfat Milk    209.615385
Soymilk               207.272727
Tall Nonfat Milk      147.826087
Venti                 118.571429
Short Nonfat Milk      99.166667
Grande                 85.714286
Tall                   63.428571
Short                  37.000000
Doppio                 10.000000
Solo                    5.000000
Name: Calories, dtype: float64